name: subir y crear
on:
  push:
    branches:
    - main
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configuracion
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "latest"
      - name: Configurar AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws-access-key: ${{secrets.AWS_ACCESS_KEY}}
            aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
            aws-region: "us-east-1"

      - name: copiar el tfstate
        run: aws s3 cp s3://mi-bucket-gabriel-2/terraform-tfstate ./terraform.tfstate
      - name: Terraform init
        run: terraform init -reconfigure
      - name: destruir s3
        run: aws s3 rm s3://mi-bucket-gabriel-2 --recursive
      - name: terraform destroy
        run: terraform destroy -auto-approve
